use super::*;
use crate::tests::tests_xor::xor_circuit_autogenerated::XorCircuitAutogenerated;
use midnight_proofs::dev::MockProver;

#[test]
fn test_positive_xor() {
    let a = ((1u128 << 64) - 1) as u64;

    test_xor_operation(a, a, a ^ a);
}

#[test]
#[should_panic]
fn test_negative_xor() {
    let a = ((1u128 << 64) - 1) as u64;
    let b = 0;

    test_xor_operation(a, b, b);
}

fn test_xor_operation(a: u64, b: u64, result: u64) {
    let circuit = XorCircuitAutogenerated::<Fq>::new_for(
        blake2b_value_for(a),
        blake2b_value_for(b),
        blake2b_value_for(result),
    );
    let prover = MockProver::run(17, &circuit, vec![]).unwrap();

    prover.verify().unwrap();
}
