use super::*;
use crate::tests::Decompose8Config;
use crate::base_operations::rotate_63::Rotate63Config;
use midnight_proofs::circuit::SimpleFloorPlanner;
use midnight_proofs::plonk::{Circuit, Fixed};
use std::array;
use std::marker::PhantomData;

#[derive(Clone)]
pub(crate) struct Rotation63Config8bitWithResultValidation<F: PrimeField> {
    _ph: PhantomData<F>,
    rotation_63_config: Rotation63Config8bitLimbs<F>,
    fixed: Column<Fixed>,
    full_number_u64: Column<Advice>,
    limbs: [Column<Advice>; 8],
}

pub(crate) struct Rotation63Circuit8bitLimbsAutogenerated<F: PrimeField> {
    _ph: PhantomData<F>,
    input: Value<Blake2bWord>,
    result: Value<Blake2bWord>,
}

impl<F: PrimeField> Rotation63Circuit8bitLimbsAutogenerated<F> {
    pub(crate) fn new_for(input: Value<Blake2bWord>, result: Value<Blake2bWord>) -> Self {
        Self {
            _ph: PhantomData,
            input,
            result,
        }
    }
}

impl<F: PrimeField> Circuit<F> for Rotation63Circuit8bitLimbsAutogenerated<F> {
    type Config = Rotation63Config8bitWithResultValidation<F>;
    type FloorPlanner = SimpleFloorPlanner;

    fn without_witnesses(&self) -> Self {
        Self {
            _ph: PhantomData,
            input: Value::unknown(),
            result: Value::unknown(),
        }
    }

    fn configure(meta: &mut ConstraintSystem<F>) -> Self::Config {
        let full_number_u64 = meta.advice_column();
        let fixed = meta.fixed_column();
        meta.enable_equality(full_number_u64);
        meta.enable_equality(fixed);

        let limbs: [Column<Advice>; 8] = array::from_fn(|_| meta.advice_column());

        let decompose_8_chip = Decompose8Config::configure(meta, full_number_u64, limbs);

        let rotation_63_chip = Rotate63Config::configure(
            meta,
            full_number_u64,
            decompose_8_chip.q_decompose,
            decompose_8_chip.q_range,
        );

        Self::Config {
            _ph: PhantomData,
            rotation_63_config: Rotation63Config8bitLimbs {
                _ph: PhantomData,
                decompose_8_config: decompose_8_chip,
                rotation_63_config: rotation_63_chip,
            },
            fixed,
            full_number_u64,
            limbs,
        }
    }

    #[allow(unused_variables)]
    fn synthesize(
        &self,
        config: Self::Config,
        mut layouter: impl Layouter<F>,
    ) -> Result<(), Error> {
        config.rotation_63_config.decompose_8_config.populate_lookup_table(&mut layouter)?;
        layouter.assign_region(
            || "generate rotate 63",
            |mut region| {
                let mut offset = 0;
                let a_row = config
                    .rotation_63_config
                    .decompose_8_config
                    .generate_row_from_word_and_keep_row(&mut region, self.input, offset)?;
                offset += 1;
                let result = config
                    .rotation_63_config
                    .rotation_63_config
                    .generate_64_bit_rotation_from_cells(
                        &mut region,
                        &mut offset,
                        &a_row.full_number.clone(),
                        config.full_number_u64,
                        config.limbs,
                    )?;

                // Check that the calculation was performed correctly by the Rotate63 chip
                let fixed_cell = region.assign_fixed(
                    || "assign expected result",
                    config.fixed,
                    0,
                    || self.result,
                )?;
                // Constrain expected result
                region.constrain_equal(result.cell(), fixed_cell.cell())?;
                Ok(())
            },
        )?;
        Ok(())
    }
}
