use super::*;
use crate::tests::tests_rotation::limb_rotation_circuit_autogenerated::LimbRotationCircuitAutogenerated;
use midnight_proofs::dev::MockProver;

#[test]
fn test_limb_rotation_chip_should_generate_32_bit_rotation_trace_correctly() {
    let input_number = 1u128;
    let expected_result_number = input_number << 32;

    run_test_limb_rotation_autogenerated::<32>(input_number, expected_result_number);
}

#[test]
#[should_panic]
fn test_limb_rotation_chip_for_32_bits_should_panic_over_a_wrong_result() {
    let input_number = 1u128;
    let wrong_expected_result_number = (input_number << 32) + 1;

    run_test_limb_rotation_autogenerated::<32>(input_number, wrong_expected_result_number);
}

#[test]
fn test_limb_rotation_chip_should_generate_24_bit_rotation_trace_correctly() {
    let expected_result_number = 1u128;
    let input_number = expected_result_number << 24;

    run_test_limb_rotation_autogenerated::<24>(input_number, expected_result_number);
}

#[test]
#[should_panic]
fn test_limb_rotation_chip_for_24_bits_should_panic_over_a_wrong_result() {
    let input_number = 1u128;
    let wrong_expected_result_number = (input_number << 24) + 1;

    run_test_limb_rotation_autogenerated::<24>(input_number, wrong_expected_result_number);
}

#[test]
fn test_limb_rotation_chip_should_generate_16_bit_rotation_trace_correctly() {
    let input_number = 1u128 << 16;
    let expected_result_number = 1u128;

    run_test_limb_rotation_autogenerated::<16>(input_number, expected_result_number);
}

#[test]
#[should_panic]
fn test_limb_rotation_chip_for_16_bits_should_panic_over_a_wrong_result() {
    let input_number = 1u128;
    let wrong_expected_result_number = (input_number << 16) + 1;

    run_test_limb_rotation_autogenerated::<16>(input_number, wrong_expected_result_number);
}

fn run_test_limb_rotation_autogenerated<const N: usize>(
    input_number: u128,
    expected_result_number: u128,
) {
    let circuit = LimbRotationCircuitAutogenerated::<Fq, N>::new_for(
        Value::known(Blake2bWord(input_number as u64)),
        Value::known(Blake2bWord(expected_result_number as u64)),
    );
    let prover = MockProver::run(17, &circuit, vec![]).unwrap();
    prover.verify().unwrap();
}
