use super::*;
use crate::tests::tests_rotation::rotation_63_cirtuit_8bit_limbs_autogenerated::Rotation63Circuit8bitLimbsAutogenerated;
use midnight_proofs::dev::MockProver;

#[test]
fn test_rot_63_chip_should_know_how_to_create_trace_from_inputs() {
    let circuit = Rotation63Circuit8bitLimbsAutogenerated::<Fq>::new_for(
        Value::known(Blake2bWord(1u8.into())),
        Value::known(Blake2bWord(2u8.into())),
    );
    let prover = MockProver::run(17, &circuit, vec![]).unwrap();
    assert_eq!(prover.verify(), Ok(()));
}

#[test]
#[should_panic]
fn test_rot_63_chip_should_panic_over_a_wrong_result() {
    let circuit = Rotation63Circuit8bitLimbsAutogenerated::<Fq>::new_for(
        Value::known(Blake2bWord(1u8.into())),
        Value::known(Blake2bWord(3u8.into())),
    );
    let prover = MockProver::run(17, &circuit, vec![]).unwrap();
    assert_eq!(prover.verify(), Ok(()));
}
