use super::*;

use midnight_proofs::circuit::SimpleFloorPlanner;
use midnight_proofs::plonk::{Circuit, Fixed};
use std::array;
use crate::types::bit::AssignedBit;
use crate::types::blake2b_word::{AssignedBlake2bWord, Blake2bWord};
use crate::tests::Decompose8Config;

pub(crate) struct AdditionMod64Circuit8BitsAutogenerated<F: PrimeField> {
    _ph: PhantomData<F>,
    value_a: Value<Blake2bWord>,
    value_b: Value<Blake2bWord>,
    expected_result: Value<Blake2bWord>,
    expected_carry: Value<Blake2bWord>,
}

#[derive(Clone)]
pub(crate) struct AdditionMod64Config8BitsWithResultValidation<F: PrimeField> {
    _ph: PhantomData<F>,
    add_config: AdditionMod64Config8Bits<F>,
    fixed_result: Column<Fixed>,
    fixed_carry: Column<Fixed>,
    full_number_u64: Column<Advice>,
    limbs: [Column<Advice>; 8],
}

impl<F: PrimeField> Circuit<F> for AdditionMod64Circuit8BitsAutogenerated<F> {
    type Config = AdditionMod64Config8BitsWithResultValidation<F>;
    type FloorPlanner = SimpleFloorPlanner;
    type Params = ();

    fn without_witnesses(&self) -> Self {
        Self {
            _ph: PhantomData,
            value_a: Value::unknown(),
            value_b: Value::unknown(),
            expected_result: Value::unknown(),
            expected_carry: Value::unknown(),
        }
    }

    #[allow(unused_variables)]
    fn configure(meta: &mut ConstraintSystem<F>) -> Self::Config {
        let full_number_u64 = meta.advice_column();
        let limbs: [Column<Advice>; 8] = array::from_fn(|_| meta.advice_column());

        let decompose_8_config = Decompose8Config::configure(meta, full_number_u64, limbs);
        let addition_config = AdditionMod64Config::configure(
            meta,
            full_number_u64,
            limbs[0],
            decompose_8_config.q_decompose,
            decompose_8_config.q_range,
        );

        let fixed_result = meta.fixed_column();
        let fixed_carry = meta.fixed_column();
        meta.enable_equality(full_number_u64);
        meta.enable_equality(limbs[0]);
        meta.enable_equality(fixed_result);
        meta.enable_equality(fixed_carry);

        Self::Config {
            _ph: PhantomData,
            add_config: AdditionMod64Config8Bits {
                _ph: PhantomData,
                sum_8bits_config: addition_config,
                decompose_8_config,
            },
            fixed_result,
            fixed_carry,
            full_number_u64,
            limbs,
        }
    }

    #[allow(unused_variables)]
    fn synthesize(
        &self,
        config: Self::Config,
        mut layouter: impl Layouter<F>,
    ) -> Result<(), Error> {
        config.add_config.decompose_8_config.populate_lookup_table(&mut layouter)?;
        layouter.assign_region(
            || "sum",
            |mut region| {
                let mut offset = 0;
                let a_cell = config
                    .add_config
                    .decompose_8_config
                    .generate_row_from_word_and_keep_row(&mut region, self.value_a, offset)?
                    .full_number;
                offset += 1;
                let b_cell = config
                    .add_config
                    .decompose_8_config
                    .generate_row_from_word_and_keep_row(&mut region, self.value_b, offset)?
                    .full_number;
                offset += 1;

                let decompose = &config.add_config.decompose_8_config;
                let result_and_carry =
                    config.add_config.sum_8bits_config.generate_addition_rows_from_cells(
                        &mut region,
                        &mut offset,
                        &a_cell,
                        &b_cell,
                        false,
                        config.full_number_u64,
                        config.limbs,
                    )?;

                Self::assert_word_value(
                    &mut region,
                    &result_and_carry.0.full_number,
                    config.fixed_result,
                    self.expected_result,
                )?;
                Self::assert_carry_value(
                    &mut region,
                    &result_and_carry.1,
                    config.fixed_carry,
                    self.expected_carry,
                )?;
                Ok(())
            },
        )?;
        Ok(())
    }
}

impl<F: PrimeField> AdditionMod64Circuit8BitsAutogenerated<F> {
    fn assert_word_value(
        region: &mut Region<'_, F>,
        cell: &AssignedBlake2bWord<F>,
        fixed_column: Column<Fixed>,
        expected_value: Value<Blake2bWord>,
    ) -> Result<(), Error> {
        let fixed_cell =
            region.assign_fixed(|| "assign fixed", fixed_column, 0, || expected_value)?;
        region.constrain_equal(cell.cell(), fixed_cell.cell())?;
        Ok(())
    }

    fn assert_carry_value(
        region: &mut Region<'_, F>,
        cell: &AssignedBit<F>,
        fixed_column: Column<Fixed>,
        expected_value: Value<Blake2bWord>,
    ) -> Result<(), Error> {
        let fixed_cell =
            region.assign_fixed(|| "assign fixed", fixed_column, 0, || expected_value)?;
        region.constrain_equal(cell.cell(), fixed_cell.cell())?;
        Ok(())
    }
}

impl<F: PrimeField> AdditionMod64Circuit8BitsAutogenerated<F> {
    pub(crate) fn new_for(
        value_a: Value<Blake2bWord>,
        value_b: Value<Blake2bWord>,
        expected_result: Value<Blake2bWord>,
        expected_carry: Value<Blake2bWord>,
    ) -> Self {
        Self {
            _ph: PhantomData,
            value_a,
            value_b,
            expected_result,
            expected_carry,
        }
    }
}
